### ISSUE TITLE
Jakis blad 

### ISSUE THREAD

**Issue by OlekSklorz** [zuliq/test0#2]
dsadsadsadsadsafsafiasjfisajifjasifjia

**Comment by zuliq** [comment]
PAANIE DEJ PAN SPOKOJ. DO WIDZENIA

**Comment by OlekSklorz** [comment]
i co z tym bledem??

**Comment by OlekSklorz** [comment]
# _adsadadsadads**dsadsadsadsadaddsadsad**_ :dancer:

**Comment by SKapturska** [comment]
Panie!!! nie działa

**Comment by PProstacki** [comment]
nie omisz komputerow, wez to napraw

**Comment by PProstacki** [comment]
halo programisty!!!

**Comment by zuliq** [comment]
PROSZE SIĘ PAŁOWAĆ

**Comment by PProstacki** [comment]
nie jeste kasztanem !!!! gon sie leszczu

**Comment by zuliq** [comment]
koniec. niczego nie bedzie
